[package]
name = "nes-frontend"
version = "0.1.0"
authors = ["Robin Quint <rob2309@hotmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes-core = { path="../nes-core" }